django_music/music/history/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:artist_id>/', views.song, name='song')
]

django_music/music/music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('history/', include('history.urls')),
    path('admin/', admin.site.urls),
]

django_music/music/history/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    artist_text = models.CharField(max_length=200)

    def __str__(self):
        return self.artist_text

class Song(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    song_text = models.CharField(max_length=200)

    def __str__(self):
        return self.song_text

django_music/music/history/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse
from .models import Artist, Song


def index(request):
    artist_list = Artist.objects.all()
    context = {'artist_list': artist_list}
    return render(request, 'history/index.html', context)

# def song(request, artist_id):
#     song_list = Song.objects.all()
#     return render(request, 'history/song.html', )
    
def song(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    return render(request, 'history/songs.html', {'artist': artist})

django_music/music/history/templates/history/index.html
<h1>Artists</h1>
<ul>
    {% for a in artist_list %}
        <li><a href="/history/{{a.id}}">{{ a.artist_text }}<a/></li>
    {% endfor %}
</ul>

django_music/music/history/templates/history/songs.html
<h2>{{ artist.artist_text }}</h2>
<h3>Songs:</h3>

<ul>
{% for s in artist.song_set.all %}
    <li>{{ s.song_text }}</li>

{% endfor %}
</ul>